### ISSUE TITLE
When submitting a survey result, the OpenForm step incorrectly states Comments are optional

### ISSUE THREAD

**Issue by filmaj** [slack-samples/deno-simple-survey#8]
If you submit a survey result with no comment, when running locally, you will see this error in your terminal:

```
2023-03-31 17:46:22 [error] [Wf051B1J9MA7] (Trace=Tr051DRY3HN0) Execution failed for workflow 'Respond to a survey'
	parameter_validation_failed - Null value for non-nullable parameter `comments`
```

If you submit a survey result with a comment, things work as expected.

Easy workaround is to set the Comment field in the survey result submission OpenForm step to required.

**Comment by rampion** [comment]
Related to #24

**Comment by hello-ashleyintech** [comment]
Fixed by https://github.com/slack-samples/deno-simple-survey/pull/26, which has just been merged in ✅
